In [45]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings():
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZDEwY2IxYS0yZDRjLTQ5ODEtYmY5Zi05ZjVhMDBkMjVjNzIiLCJlbWFpbCI6InB1dHRhcG9ndWFiaGlzaGVrMTAwN0BnbWFpbC5jb20iLCJpYXQiOjE3MzU2Mjk5MTksImV4cCI6MTc2NzE2NTkxOX0.XeRI2RrVfhRxjvLuZRdeeJvcCMTlaWmbJCgbwXmHrCM "
        
    }
    payload = {
        "input": "The food was delicious and the service was excellent.",
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding


In [46]:
generate_embeddings()

Generated embedding with shape: (1536,)
First 5 values: [-0.03244253 -0.00839565 -0.06356495 ... -0.00225143  0.05896459
 -0.03152246]
Vector norm: 1.0000000296607552


array([-0.03244253, -0.00839565, -0.06356495, ..., -0.00225143,
        0.05896459, -0.03152246])

### vector embeddings

In [47]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZDEwY2IxYS0yZDRjLTQ5ODEtYmY5Zi05ZjVhMDBkMjVjNzIiLCJlbWFpbCI6InB1dHRhcG9ndWFiaGlzaGVrMTAwN0BnbWFpbC5jb20iLCJpYXQiOjE3MzU2Mjk5MTksImV4cCI6MTc2NzE2NTkxOX0.XeRI2RrVfhRxjvLuZRdeeJvcCMTlaWmbJCgbwXmHrCM "
        
    }
    payload = {
        "input": "text",
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding


In [48]:
data_1 = generate_embeddings("My name is Abhishek")

Generated embedding with shape: (1536,)
First 5 values: [-0.00595438  0.02953021 -0.03836918 ... -0.01522965  0.01196526
 -0.01151954]
Vector norm: 1.0000000715440285


In [49]:
data_1

array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
        0.01196526, -0.01151954])

In [50]:
data_2 = generate_embeddings("Abhishek is working as AI Engineer")

Generated embedding with shape: (1536,)
First 5 values: [-0.00595438  0.02953021 -0.03836918 ... -0.01522965  0.01196526
 -0.01151954]
Vector norm: 1.0000000715440285


In [51]:
data_2

array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
        0.01196526, -0.01151954])

In [52]:
data_3 = generate_embeddings("people also call me Abhishek")

Generated embedding with shape: (1536,)
First 5 values: [-0.00595438  0.02953021 -0.03836918 ... -0.01522965  0.01196526
 -0.01151954]
Vector norm: 1.0000000715440285


In [53]:
data_3

array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
        0.01196526, -0.01151954])

### how search engine happens with chromadb

In [54]:
import numpy as np

In [55]:
data_1, data_2, data_3

(array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
         0.01196526, -0.01151954]),
 array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
         0.01196526, -0.01151954]),
 array([-0.00595438,  0.02953021, -0.03836918, ..., -0.01522965,
         0.01196526, -0.01151954]))

In [56]:
cosign_similarity = np.dot(data_1, data_2)/(np.linalg.norm(data_1)*np.linalg.norm(data_2))
cosign_similarity

1.0000000000000002

In [57]:
cosign_distance = 1 - cosign_similarity
cosign_distance

-2.220446049250313e-16

In [58]:
cosign_similarity2 = np.dot(data_1, data_3)/(np.linalg.norm(data_1)*np.linalg.norm(data_3))
cosign_similarity2


1.0000000000000002

In [59]:
1-cosign_similarity2

-2.220446049250313e-16

In [60]:
import sqlite3
print(sqlite3.sqlite_version)


3.22.0
